// Generated by CoffeeScript 1.6.2
(function() {
  var __slice = [].slice;

  console.log("i'm index");

  require('./a');

  module.exports = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, ['called with args: '].concat(__slice.call(args)));
  };

}).call(this);
