// Generated by CoffeeScript 1.6.2
(function() {
  var debug, originalLog,
    __slice = [].slice;

  debug = require('debug')('fantomo:patch');

  originalLog = console.log;

  console.warn = console.warning = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (-1 === args[0].indexOf('CoreText performance note:', 0)) {
      return originalLog.apply(null, args);
    }
  };

}).call(this);
