// Generated by CoffeeScript 1.6.3
(function() {
  var crypto, debug, fs, path, request;

  debug = require('debug')('fantomo:lib:utils');

  fs = require('fs');

  crypto = require('crypto');

  path = require('path');

  request = require('request');

  module.exports.cache_url = function(opts, fn) {
    var callback, filename, filepath, md5sum, req;
    if (opts.url == null) {
      throw "An url is mandatory";
    }
    if (opts.dir == null) {
      opts.dir = '/tmp';
    }
    if (opts.prefix == null) {
      opts.prefix = 'cache-';
    }
    if (opts.suffix == null) {
      opts.suffix = '';
    }
    md5sum = crypto.createHash('md5');
    md5sum.update(opts.url);
    filename = opts.prefix + md5sum.digest('hex') + opts.suffix;
    filepath = path.join(opts.dir, filename);
    if (fs.existsSync(filepath)) {
      debug("Cached version of " + opts.url + " exists at " + filepath);
      fn(null, filepath);
    } else {
      debug("Caching " + opts.url + " to " + filepath);
      callback = function(err, res, body) {
        if (err) {
          throw err;
        }
        debug("Cached " + body.length + " bytes");
        return fn(err, filepath);
      };
      req = request(opts.url, callback);
      req.pipe(fs.createWriteStream(filepath));
    }
    return filepath;
  };

}).call(this);
