// Generated by CoffeeScript 1.6.3
(function() {
  var Fantomo, bot, debug;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  debug = require('debug')('fantomo:examples:bot-debug');

  Fantomo = require('..');

  bot = new Fantomo({
    verbose: true
  });

  bot.on('ready', function() {
    debug('bot is ready');
    return this.open('http://moul.github.io/');
  });

  bot.on('open', function(path) {
    return debug("browser is open (" + path + ")");
  });

}).call(this);
