// Generated by CoffeeScript 1.6.2
(function() {
  var Fantomo, bot;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Fantomo = require('..');

  bot = new Fantomo({
    verbose: true,
    browser: {
      verbose: true
    }
  });

  bot.on('ready', function() {
    var _this = this;

    console.log('bot is ready');
    return setTimeout((function() {
      return _this.open('http://moul.github.io/');
    }), 3000);
  });

  bot.on('open', function() {
    return console.log('opened');
  });

}).call(this);
