// Generated by CoffeeScript 1.6.3
(function() {
  var Fantomo, app, bot, debug;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  debug = require('debug')('fantomo:examples:cache-url');

  app = require('./express');

  app.listen(12345);

  Fantomo = require('..');

  bot = new Fantomo({
    verbose: true,
    url: 'http://127.0.0.1:12345/'
  });

  bot.on('open', function(path) {
    debug("browser is open (" + path + ")");
    return bot.cache_url('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.js', function(err, filepath) {
      if (err) {
        throw err;
      }
      return bot.inject(filepath, function() {
        debug('jQuery is injected');
        return bot.inject(function() {
          var $;
          $ = fantomo;
          return console.log($('body').text());
        });
      });
    });
  });

}).call(this);
