// Generated by CoffeeScript 1.6.2
(function() {
  var app, express;

  express = require('express');

  module.exports = app = express();

  app.get('/', function(req, res) {
    return res.send('Hello World');
  });

}).call(this);
