// Generated by CoffeeScript 1.6.2
(function() {
  var Fantomo, app, bot, debug;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  debug = require('debug')('fantomo:examples:bot-debug');

  app = require('./express');

  app.listen(12345);

  Fantomo = require('..');

  bot = new Fantomo({
    verbose: true,
    browser: {
      verbose: true
    }
  });

  bot.on('ready', function() {
    debug('bot is ready');
    return this.open('http://127.0.0.1:12345/');
  });

  bot.browser.on('ready', function() {
    return debug('browser is ready');
  });

  bot.browser.on('open', function(path) {
    debug("browser is open (" + path + ")");
    return bot.inject('./inject');
  });

}).call(this);
