// Generated by CoffeeScript 1.6.3
(function() {
  var Fantomo, app, bot, debug;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  debug = require('debug')('fantomo:examples:inject-dir');

  app = require('./express');

  app.listen(12345);

  Fantomo = require('..');

  bot = new Fantomo({
    verbose: true,
    url: 'http://127.0.0.1:12345/'
  });

  bot.on('open', function(path) {
    var callback;
    debug("browser is open (" + path + ")");
    callback = function(ret) {
      return console.log("callback: ret=" + ret);
    };
    return bot.inject('./inject/index', callback, 1, 2, 3);
  });

}).call(this);
